# DAS: data analytic stack
name: das
channels:
- defaults
- conda
- conda-forge
dependencies:
- python=3.6
- scipy
- numpy
- pandas
- scikit-learn
- matplotlib
- seaborn
- spyder
- pydot
- h5py
- pip
- pip:
  - tensorflow 
  - keras
  - flask
  - gevent
  - requests
